# https://www.cmor-faculty.rice.edu/~heinken/latex/symbols.pdf
# LATEX Mathematical Symbols
# The more unusual symbols are not defined in base LATEX (NFSS) and require \usepackage{amssymb}
# Use the pair \lefts1 and \rights1 to match height of delimiters s1 and s2 to the height of their contents,
# e.g. \left| expr \right| -or- \left\{ expr \right\} -or- \left\Vert expr \right.

from typing import List

SYM_GREEK = [
    [r'\alpha', r'\kappa', r'\psi', r'\digamma', r'\Delta', r'\Theta'],
    [r'\beta', r'\lambda', r'\rho', r'\varepsilon', r'\Gamma', r'\Upsilon'],
    [r'\chi', r'\mu', r'\sigma', r'\varkappa', r'\Lambda', r'\Xi'],
    [r'\delta', r'\nu', r'\tau', r'\varphi', r'\Omega', ''],
    [r'\epsilon', r'o', r'\theta', r'\varpi', r'\Phi', r'\aleph'],
    [r'\eta', r'\omega', r'\upsilon', r'\varrho', r'\Pi', r'\beth'],
    [r'\gamma', r'\phi', r'\xi', r'\varsigma', r'\Psi', r'\daleth'],
    [r'\iota', r'\pi', r'\zeta', r'\vartheta', r'\Sigma', r'\gimel'],
]
SYM_MATH = [
    [r'\frac{abc}{xyz}', r'\overline{abc}', r'\overrightarrow{abc}'],
    ["f'", r'\underline{abc}', r'\overleftarrow{abc}'],
    [r'\sqrt{abc}', r'\widehat{abc}', r'\overbrace{abc}'],
    [r'\sqrt[n]{abc}', r'\widetilde{abc}', r'\underbrace{abc}'],
]
SYM_DELIM = [
    ['|', r'\{', r'\lfloor', '/', r'\Uparrow', r'\llcorner'],
    [r'\vert', r'\}', r'\rfloor', r'\backslash', r'\uparrow', r'\lrcorner'],
    [r'\|', r'\langle', r'\lceil', '[', r'\Downarrow', r'\ulcorner'],
    [r'\Vert', r'\rangle', r'\rceil', ']', r'\downarrow', r'\urcorner'],
]
SYM_LARGE = [ # Displayed formulae show larger version.
    [r'\sum', r'\int', r'\biguplus', r'\bigoplus', r'\bigvee'],
    [r'\prod', r'\oint', r'\bigcap', r'\bigotimes', r'\bigwedge'],
    [r'\coprod', r'\iint', r'\bigcup', r'\bigodot', r'\bigsqcup'],    
]
SYM_FUNC = [ # Should appear in Roman, not Italic.
    [r'\arccos', r'\arcsin', r'\arctan', r'\arg'],
    [r'\cos', r'\cosh', r'\cot', r'\coth'],
    [r'\csc', r'\deg', r'\det', r'\dim'],
    [r'\exp', r'\gcd', r'\hom', r'\inf'],
    [r'\ker', r'\lg', r'\lim', r'\liminf'],
    [r'\limsup', r'\ln ', r'\log', r'\max'],
    [r'\min', r'\Pr', r'\sec', r'\sin'],
    [r'\sinh', r'\sup', r'\tan', r'\tanh'],
]
SYM_OPS_1 = [
    [r'\ast', r'\pm', r'\cap', r'\lhd'],
    [r'\star', r'\mp', r'\cup', r'\rhd'],
    [r'\cdot', r'\amalg', r'\uplus', r'\triangleleft'],
    [r'\circ', r'\odot', r'\sqcap', r'\triangleright'],
    [r'\bullet', r'\ominus', r'\sqcup', r'\unlhd'],
    [r'\bigcirc', r'\oplus', r'\wedge', r'\unrhd'],
    [r'\diamond', r'\oslash', r'\vee', r'\bigtriangledown'],
    [r'\times', r'\otimes', r'\dagger', r'\bigtriangleup'],
    [r'\div', r'\wr', r'\ddagger', r'\setminus'],
    [r'\centerdot', r'\Box', r'\barwedge', r'\veebar'],
    [r'\circledast', r'\boxplus', r'\curlywedge', r'\curlyvee'],
    [r'\circledcirc', r'\boxminus', r'\Cap', r'\Cup'],
    [r'\circleddash', r'\boxtimes', r'\bot', r'\top'],
    [r'\dotplus', r'\boxdot', r'\intercal', r'\rightthreetimes'],
    [r'\divideontimes', r'\square', r'\doublebarwedge', r'\leftthreetimes'],
]
SYM_OPS_2 = [
    [r'\equiv', r'\leq', r'\geq', r'\perp'], 
    [r'\cong', r'\prec', r'\succ', r'\mid'], 
    [r'\neq', r'\preceq', r'\succeq', r'\parallel'], 
    [r'\sim', r'\ll', r'\gg', r'\bowtie'], 
    [r'\simeq', r'\subset', r'\supset', r'\Join'], 
    [r'\approx', r'\subseteq', r'\supseteq', r'\ltimes'], 
    [r'\asymp', r'\sqsubset', r'\sqsupset', r'\rtimes'], 
    [r'\doteq', r'\sqsubseteq', r'\sqsupseteq', r'\smile'], 
    [r'\propto', r'\dashv', r'\vdash', r'\frown'], 
    [r'\models', r'\in', r'\ni', r'\notin'],
    [r'\approxeq', r'\leqq', r'\geqq', r'\lessgtr'],
    [r'\thicksim', r'\leqslant', r'\geqslant', r'\lesseqgtr'],
    [r'\backsim', r'\lessapprox', r'\gtrapprox', r'\lesseqqgtr'],
    [r'\backsimeq', r'\lll', r'\ggg', r'\gtreqqless'],
    [r'\triangleq', r'\lessdot', r'\gtrdot', r'\gtreqless'],
    [r'\circeq', r'\lesssim', r'\gtrsim', r'\gtrless'],
    [r'\bumpeq', r'\eqslantless', r'\eqslantgtr', r'\backepsilon'],
    [r'\Bumpeq', r'\precsim', r'\succsim', r'\between'],
    [r'\doteqdot', r'\precapprox', r'\succapprox', r'\pitchfork'],
]
SYM_OPS_3 = [
    [r'\thickapprox', r'\Subset', r'\Supset', r'\shortmid'],
    [r'\fallingdotseq', r'\subseteqq', r'\supseteqq', r'\smallfrown'],
    [r'\risingdotseq', r'\sqsubset', r'\sqsupset', r'\smallsmile'],
    [r'\varpropto', r'\preccurlyeq', r'\succcurlyeq', r'\Vdash'],
    [r'\therefore', r'\curlyeqprec', r'\curlyeqsucc', r'\vDash'],
    [r'\because', r'\blacktriangleleft', r'\blacktriangleright', r'\Vvdash'],
    [r'\eqcirc', r'\trianglelefteq', r'\trianglerighteq', r'\shortparallel'],
    [r'\neq', r'\vartriangleleft', r'\vartriangleright', r'\nshortparallel'],
    [r'\ncong', r'\nleq', r'\ngeq', r'\nsubseteq'],
    [r'\nmid', r'\nleqq', r'\ngeqq', r'\nsupseteq'],
    [r'\nparallel', r'\nleqslant', r'\ngeqslant', r'\nsubseteqq'],
    [r'\nshortmid', r'\nless', r'\ngtr', r'\nsupseteqq'],
    [r'\nshortparallel', r'\nprec', r'\nsucc', r'\subsetneq'],
    [r'\nsim', r'\npreceq', r'\nsucceq', r'\supsetneq'],
]
SYM_OPS_4 = [
    [r'\nVDash', r'\precnapprox', r'\succnapprox', r'\subsetneqq'],
    [r'\nvDash', r'\precnsim', r'\succnsim', r'\supsetneqq'],
    [r'\nvdash', r'\lnapprox', r'\gnapprox', r'\varsubsetneq'],
    [r'\ntriangleleft', r'\lneq', r'\gneq', r'\varsupsetneq'],
    [r'\ntrianglelefteq', r'\lneqq', r'\gneqq', r'\varsubsetneqq'],
    [r'\ntriangleright', r'\lnsim', r'\gnsim', r'\varsupsetneqq'],
    [r'\ntrianglerighteq', r'\lvertneqq', r'\gvertneqq', ''],
]
SYM_ARROW_1 = [
    [r'\leftarrow', r'\longleftarrow', r'\uparrow'],
    [r'\Leftarrow', r'\Longleftarrow', r'\Uparrow'],
    [r'\rightarrow', r'\longrightarrow', r'\downarrow'],
    [r'\Rightarrow', r'\Longrightarrow', r'\Downarrow'],
    [r'\leftrightarrow', r'\longleftrightarrow', r'\updownarrow'],
    [r'\Leftrightarrow', r'\Longleftrightarrow', r'\Updownarrow'],
    [r'\mapsto', r'\longmapsto', r'\nearrow'],
    [r'\hookleftarrow', r'\hookrightarrow', r'\searrow'],
    [r'\leftharpoonup', r'\rightharpoonup', r'\swarrow'],
    [r'\leftharpoondown', r'\rightharpoondown', r'\nwarrow'],
    [r'\rightleftharpoons', r'\leadsto', ''],
]
SYM_ARROW_2 = [
    [r'\dashrightarrow', r'\dashleftarrow', r'\leftleftarrows'],
    [r'\leftrightarrows', r'\Lleftarrow', r'\twoheadleftarrow'],
    [r'\leftarrowtail', r'\looparrowleft', r'\leftrightharpoons'],
    [r'\curvearrowleft', r'\circlearrowleft', r'\Lsh'],
    [r'\upuparrows', r'\upharpoonleft', r'\downharpoonleft'],
    [r'\multimap', r'\leftrightsquigarrow', r'\rightrightarrows'],
    [r'\rightleftarrows', r'\rightrightarrows', r'\rightleftarrows'],
    [r'\twoheadrightarrow', r'\rightarrowtail', r'\looparrowright'],
    [r'\rightleftharpoons', r'\curvearrowright', r'\circlearrowright'],
    [r'\Rsh', r'\downdownarrows', r'\upharpoonright'],
    [r'\downharpoonright', r'\rightsquigarrow', ''],
    [r'\nleftarrow', r'\nrightarrow', r'\nLeftarrow'],
    [r'\nRightarrow', r'\nleftrightarrow', r'\nLeftrightarrow'],
]
SYM_MISC = [
    [r'\infty', r'\forall', r'\Bbbk', r'\wp'],
    [r'\nabla', r'\exists', r'\bigstar', r'\angle'],
    [r'\partial', r'\nexists', r'\diagdown', r'\measuredangle'],
    [r'\eth', r'\emptyset', r'\diagup', r'\sphericalangle'],
    [r'\clubsuit', r'\varnothing', r'\Diamond', r'\complement'],
    [r'\diamondsuit', r'\imath', r'\Finv', r'\triangledown'],
    [r'\heartsuit', r'\jmath', r'\Game', r'\triangle'],
    [r'\spadesuit', r'\ell', r'\hbar', r'\vartriangle'],
    [r'\cdots', r'\iiiint', r'\hslash', r'\blacklozenge'],
    [r'\vdots', r'\iiint', r'\lozenge', r'\blacksquare'],
    [r'\ldots', r'\iint', r'\mho', r'\blacktriangle'],
    [r'\ddots', r'\sharp', r'\prime', r'\blacktriangledown'],
    [r'\Im', r'\flat', r'\square', r'\backprime'],
    [r'\Re', r'\natural', r'\surd', r'\circledS'],
]
SYM_ACCENT = [
    [r'\acute{a}', r'\bar{a}', r'\Acute{\Acute{A}}', r'\Bar{\Bar{A}}'],
    [r'\breve{a}', r'\check{a}', r'\Breve{\Breve{A}}', r'\Check{\Check{A}}'],
    [r'\ddot{a}', r'\dot{a}', r'\Ddot{\Ddot{A}}', r'\Dot{\Dot{A}}'],
    [r'\grave{a}', r'\hat{a}', r'\Grave{\Grave{A}}', r'\Hat{\Hat{A}}'],
    [r'\tilde{a}', r'\vec{a}', r'\Tilde{\Tilde{A}}', r'\Vec{\Vec{A}}'],
]
SYM_STYLE = [
    [r'\mathcal{ABCDEFGHIJKLMNOPQRSTUVWXYZ}'],
    [r'\mathbb{ABCDEFGHIJKLMNOPQRSTUVWXYZ}'],
    [r'\mathfrak{ABCDEFGHIJKLMNOPQRSTUVWXYZabc123}'],
    [r'\mathsf{ABCDEFGHIJKLMNOPQRSTUVWXYZabc123}'],
    [r'\mathbf{ABCDEFGHIJKLMNOPQRSTUVWXYZabc123}'],
]
SYM_FONT = [
    [r'\displaystyle \int f^{-1}(x-x_a)\,dx}'],
    [r'\textstyle \int f^{-1}(x-x_a)\,dx}'],
    [r'\scriptstyle \int f^{-1}(x-x_a)\,dx}'],
    [r'\scriptscriptstyle \int f^{-1}(x-x_a)\,dx}'],
]
SYM_ALL = [
    r'\aleph',
    r'\alpha',
    r'\amalg',
    r'\angle',
    r'\approx',
    r'\approxeqy',
    r'\arccos',
    r'\arcsin',
    r'\arctan',
    r'\arg',
    r'\Arrownot',
    r'\arrownot',
    r'\ast',
    r'\asymp',
    r'\backepsilony',
    r'\backprimey',
    r'\backsimy',
    r'\backsimeqy',
    r'\backslash',
    r'\baro',
    r'\barwedgey',
    r'\bbslash',
    r'\becausey',
    r'\beta',
    r'\bethy',
    r'\betweeny',
    r'\bigbox',
    r'\bigcap',
    r'\bigcirc',
    r'\bigcup',
    r'\bigcurlyvee',
    r'\bigcurlywedge',
    r'\biginterleave',
    r'\bignplus',
    r'\bigodot',
    r'\bigoplus',
    r'\bigotimes',
    r'\bigparallel',
    r'\bigsqcap',
    r'\bigsqcup',
    r'\bigstary',
    r'\bigtriangledown',
    r'\bigtriangledown',
    r'\bigtriangleup',
    r'\bigtriangleup',
    r'\biguplus',
    r'\bigvee',
    r'\bigwedge',
    r'\binampersand',
    r'\bindnasrepma',
    r'\blacklozengey',
    r'\blacksquarey',
    r'\blacktriangley',
    r'\blacktriangledowny',
    r'\blacktrianglelefty',
    r'\blacktrianglerighty',
    r'\bmod',
    r'\bot',
    r'\bowtie',
    r'\boxast',
    r'\boxbar',
    r'\boxbox',
    r'\boxbslash',
    r'\boxcircle',
    r'\boxdot',
    r'\boxdoty',
    r'\boxempty',
    r'\boxminusy',
    r'\boxplusy',
    r'\boxslash',
    r'\boxtimesy',
    r'\bullet',
    r'\Bumpeqy',
    r'\bumpeqy',
    r'\Capy',
    r'\cap',
    r'\cdot',
    r'\cdotp',
    r'\cdots',
    r'\centerdoty',
    r'\checkmarky',
    r'\chi',
    r'\circ',
    r'\circeqy',
    r'\circlearrowlefty',
    r'\circlearrowrighty',
    r'\circledasty',
    r'\circledcircy',
    r'\circleddashy',
    r'\circledRy',
    r'\circledSy',
    r'\clubsuit',
    r'\colon',
    r'\complementy',
    r'\cong',
    r'\coprod',
    r'\copyright',
    r'\cos',
    r'\cosh',
    r'\cot',
    r'\coth',
    r'\csc',
    r'\Cupy',
    r'\cup',
    r'\curlyeqprecy',
    r'\curlyeqsuccy',
    r'\curlyveey',
    r'\curlyveedownarrow',
    r'\curlyveeuparrow',
    r'\curlywedgey',
    r'\curlywedgedownarrow',
    r'\curlywedgeuparrow',
    r'\curvearrowlefty',
    r'\curvearrowrighty',
    r'\dag',
    r'\d',
    r'\ddagger',
    r'\ddots',
    r'\deg',
    r'\Delta',
    r'\delta',
    r'\det',
    r'\diamond',
    r'\diamondsuit',
    r'\digammay',
    r'\dim',
    r'\div',
    r'\divideontimesy',
    r'\Doteqy',
    r'\doteq',
    r'\doteqdoty',
    r'\dotplusy',
    r'\dots',
    r'\doublebarwedgey',
    r'\doublecapy',
    r'\doublecupy',
    r'\Downarrow',
    r'\downarrow',
    r'\downdownarrowsy',
    r'\downharpoonlefty',
    r'\downharpoonrighty',
    r'\ell',
    r'\emptyset',
    r'\epsilon',
    r'\eqcircy',
    r'\eqsimy',
    r'\eqslantgtry',
    r'\eqslantlessy',
    r'\equiv',
    r'\eta',
    r'\ethy',
    r'\exists',
    r'\exp',
    r'\fallingdotseqy',
    r'\fatbslash',
    r'\fatsemi',
    r'\fatslash',
    r'\flat',
    r'',
    r'\forall',
    r'\frown',
    r'\Gamma',
    r'\gamma',
    r'\gcd',
    r'\geq',
    r'\geqqy',
    r'\geqslanty',
    r'\gg',
    r'\gggy',
    r'\gggtry',
    r'\gimely',
    r'\gnapproxy',
    r'\gneqy',
    r'\gneqqy',
    r'\gnsimy',
    r'\gtrapproxy',
    r'\gtrdoty',
    r'\gtreqlessy',
    r'\gtreqqlessy',
    r'\gtrlessy',
    r'\gtrsimy',
    r'\gvertneqqy',
    r'\hbar',
    r'\hbary',
    r'\heartsuit',
    r'\hom',
    r'\hslashy',
    r'\iff',
    r'\Im',
    r'\imath',
    r'\in',
    r'\inf',
    r'\infty',
    r'\inplus',
    r'\intercaly',
    r'\interleave',
    r'\intop',
    r'\iota',
    r'\jmath',
    r'\kappa',
    r'\ker',
    r'\Lambda',
    r'\lambda',
    r'\langle',
    r'\Lbag',
    r'\lbag',
    r'\lbrace',
    r'\lceil',
    r'\ldotp',
    r'\ldots',
    r'\Leftarrow',
    r'\leftarrow',
    r'\leftarrowtaily',
    r'\leftarrowtriangle',
    r'\leftharpoondown',
    r'\leftharpoonup',
    r'\leftleftarrowsy',
    r'\Leftrightarrow',
    r'\leftrightarrow',
    r'\leftrightarroweq',
    r'\leftrightarrowsy',
    r'\leftrightarrowtriangle',
    r'\leftrightharpoonsy',
    r'\leftrightsquigarrowy',
    r'\leftslice',
    r'\leftthreetimesy',
    r'\leq',
    r'\leqqy',
    r'\leqslanty',
    r'\lessapproxy',
    r'\lessdoty',
    r'\lesseqgtry',
    r'\lesseqqgtry',
    r'\lessgtry',
    r'\lesssimy',
    r'\lfloor',
    r'\lg',
    r'\lhook',
    r'\lightning',
    r'\lim',
    r'\liminf',
    r'\limsup',
    r'\ll',
    r'\llbracket',
    r'\llceil',
    r'\llcornery',
    r'\Lleftarrowy',
    r'\llfloor',
    r'\llly',
    r'\lllessy',
    r'\llparenthesis',
    r'\ln',
    r'\lnapproxy',
    r'\lneqy',
    r'\lneqqy',
    r'\lnsimy',
    r'\log',
    r'\Longarrownot',
    r'\longarrownot',
    r'\Longleftarrow',
    r'\longleftarrow',
    r'\Longleftrightarrow',
    r'\longleftrightarrow',
    r'\Longmapsfrom',
    r'\longmapsfrom',
    r'\Longmapsto',
    r'\longmapsto',
    r'\Longrightarrow',
    r'\longrightarrow',
    r'\looparrowlefty',
    r'\looparrowrighty',
    r'\lozengey',
    r'\lrcornery',
    r'\Lshy',
    r'\ltimes',
    r'\maltesey',
    r'\Mapsfrom',
    r'\mapsfrom',
    r'\Mapsfromchar',
    r'\mapsfromchar',
    r'\Mapsto',
    r'\Mapstochar',
    r'\mapstochar',
    r'\max',
    r'\measuredangley',
    r'\merge',
    r'\mhoy',
    r'\mid',
    r'\min',
    r'\minuso',
    r'\models',
    r'\moo',
    r'\mp',
    r'\mu',
    r'\multimapy',
    r'\nabla',
    r'\napprox',
    r'\natural',
    r'\ncongy',
    r'\nearrow',
    r'\neg',
    r'\neq',
    r'\nexistsy',
    r'\ngeqy',
    r'\ngeqqy',
    r'\ngeqslanty',
    r'\ngtry',
    r'\ni',
    r'\niplus',
    r'\nLeftarrowy',
    r'\nleftarrowy',
    r'\nLeftrightarrowy',
    r'\nleftrightarrowy',
    r'\nleqy',
    r'\nleqqy',
    r'\nleqslanty',
    r'\nlessy',
    r'\nmidy',
    r'\nnearrow',
    r'\nnwarrow',
    r'\not',
    r'\notin',
    r'\nparallely',
    r'\nplus',
    r'\nprecy',
    r'\npreceqy',
    r'\nRightarrowy',
    r'\nrightarrowy',
    r'\nshortmidy',
    r'\nshortparallely',
    r'\nsimy',
    r'\nsubseteqy',
    r'\nsubseteqqy',
    r'\nsuccy',
    r'\nsucceqy',
    r'\nsupseteqy',
    r'\nsupseteqqy',
    r'\ntrianglelefty',
    r'\ntrianglelefteqy',
    r'\ntrianglelefteqslant',
    r'\ntrianglerighty',
    r'\ntrianglerighteqy',
    r'\ntrianglerighteqslant',
    r'\nu',
    r'\nVDashy',
    r'\nVdashy',
    r'\nvDashy',
    r'\nvdashy',
    r'\nwarrow',
    r'\obar',
    r'\oblong',
    r'\obslash',
    r'\odot',
    r'\ogreaterthan',
    r'\ointop',
    r'\olessthan',
    r'\Omega',
    r'\omega',
    r'\ominus',
    r'\oplus',
    r'\oslash',
    r'\otimes',
    r'\ovee',
    r'\owedge',
    r'\P',
    r'\parallel',
    r'\partial',
    r'\perp',
    r'\Phi',
    r'\phi',
    r'\Pi',
    r'\pi',
    r'\pitchforky',
    r'\pm',
    r'\Pr',
    r'\prec',
    r'\precapproxy',
    r'\preccurlyeqy',
    r'\preceq',
    r'\precnapproxy',
    r'\precneqqy',
    r'\precnsimy',
    r'\precsimy',
    r'\prime',
    r'\prod',
    r'\propto',
    r'\Psi',
    r'\psi',
    r'\rangle',
    r'\Rbag',
    r'\rbag',
    r'\rbrace',
    r'\rceil',
    r'\Re',
    r'\Relbar',
    r'\relbar',
    r'\restrictiony',
    r'\rfloor',
    r'\rho',
    r'\rhook',
    r'\Rightarrow',
    r'\rightarrow',
    r'\rightarrowtaily',
    r'\rightarrowtriangle',
    r'\rightharpoondown',
    r'\rightharpoonup',
    r'\rightleftarrowsy',
    r'\rightleftharpoons',
    r'\rightleftharpoonsy',
    r'\rightrightarrowsy',
    r'\rightslice',
    r'\rightsquigarrowy',
    r'\rightthreetimesy',
    r'\risingdotseqy',
    r'\rmoustache',
    r'\rrbracket',
    r'\rrceil',
    r'\rrfloor',
    r'\Rrightarrowy',
    r'\rrparenthesis',
    r'\Rshy',
    r'\rtimesy',
    r'\S',
    r'\searrow',
    r'\sec',
    r'\setminus',
    r'\sharp',
    r'\shortdownarrow',
    r'\shortleftarrow',
    r'\shortmidy',
    r'\shortparallely',
    r'\shortrightarrow',
    r'\shortuparrow',
    r'\simeq',
    r'\sin',
    r'\sinh',
    r'\smallfrowny',
    r'\smallint',
    r'\smallsetminusy',
    r'\smallsmiley',
    r'\smile',
    r'\spadesuit',
    r'\sphericalangley',
    r'\sqcap',
    r'\sqcup',
    r'\sqrt',
    r'\sqsubsety',
    r'\sqsubseteq',
    r'\sqsupsety',
    r'\sqsupseteq',
    r'\squarey',
    r'\ssearrow',
    r'\sslash',
    r'\sswarrow',
    r'\star',
    r'\Subsety',
    r'\subset',
    r'\subseteq',
    r'\subseteqqy',
    r'\subsetneqy',
    r'\subsetneqqy',
    r'\subsetplus',
    r'\subsetpluseq',
    r'\succ',
    r'\succapproxy',
    r'\succcurlyeqy',
    r'\succeq',
    r'\succnapproxy',
    r'\succneqqy',
    r'\succnsimy',
    r'\succsimy',
    r'\sum',
    r'\sup',
    r'\Supsety',
    r'\supset',
    r'\supseteq',
    r'\supseteqqy',
    r'\supsetneqy',
    r'\supsetneqqy',
    r'\supsetplus',
    r'\supsetpluseq',
    r'\surd',
    r'\swarrow',
    r'\talloblong',
    r'\tan',
    r'\tanh',
    r'\tau',
    r'\TeX',
    r'\thereforey',
    r'\Theta',
    r'\theta',
    r'\thickapproxy',
    r'\thicksimy',
    r'\times',
    r'\top',
    r'\triangle',
    r'\triangledowny',
    r'\triangleleft',
    r'\trianglelefteqy',
    r'\trianglelefteqslant',
    r'\triangleqy',
    r'\triangleright',
    r'\trianglerighteqy',
    r'\trianglerighteqslant',
    r'\twoheadleftarrowy',
    r'\twoheadrightarrowy',
    r'\ulcornery',
    r'\Uparrow',
    r'\uparrow',
    r'\Updownarrow',
    r'\updownarrow',
    r'\upharpoonlefty',
    r'\upharpoonrighty',
    r'\uplus',
    r'\Upsilon',
    r'\upsilon',
    r'\upuparrowsy',
    r'\urcornery',
    r'\varbigcirc',
    r'\varcopyright',
    r'\varcurlyvee',
    r'\varcurlywedge',
    r'\varepsilon',
    r'\varkappay',
    r'\varnothingy',
    r'\varoast',
    r'\varobar',
    r'\varobslash',
    r'\varocircle',
    r'\varodot',
    r'\varogreaterthan',
    r'\varolessthan',
    r'\varominus',
    r'\varoplus',
    r'\varoslash',
    r'\varotimes',
    r'\varovee',
    r'\varowedge',
    r'\varphi',
    r'\varpi',
    r'\varproptoy',
    r'\varrho',
    r'\varsigma',
    r'\varsubsetneqy',
    r'\varsubsetneqqy',
    r'\varsupsetneqy',
    r'\varsupsetneqqy',
    r'\vartheta',
    r'\vartimes',
    r'\vartriangley',
    r'\vartrianglelefty',
    r'\vartrianglerighty',
    r'\Vdashy',
    r'\vDashy',
    r'\vdash',
    r'\vdots',
    r'\vee',
    r'\veebary',
    r'\Vert',
    r'\vert',
    r'\Vvdashy',
    r'\wedge',
    r'\wp',
    r'\wr',
    r'\Xi',
    r'\xi',
    r'\Ydown',
    r'\yeny',
    r'\Yleft',
]

def make_pattern(tables: List[List[List[str]]]) -> str:
    cells = [cell for table in tables for row in table for cell in row if cell]
    return f"^({'|'.join(cells)})$".replace('\\', '\\\\')

PAT_GREEK = make_pattern([SYM_GREEK])
PAT_FUNC = make_pattern([SYM_FUNC])
PAT_OPREL = make_pattern([SYM_OPS_1, SYM_OPS_2, SYM_OPS_3, SYM_OPS_4])
PAT_ARROW = make_pattern([SYM_ARROW_1, SYM_ARROW_2])
PAT_MISC = make_pattern([SYM_MISC])
